Update arch-install for paru.

diff --git a/help/.config/help/arch-install b/help/.config/help/arch-install
--- a/help/.config/help/arch-install
+++ b/help/.config/help/arch-install
@@ -7,7 +7,7 @@ LOG=/root/installation.log
 report() {
     # $1 is success message
     # $2 is failure message
-    [ $? -eq 0 ] && echo "$1" || echo "$2" >> $LOG
+    [ $? -eq 0 ] && echo "$1" || echo "$2" >>$LOG
 }
 ######################################################
 # Test if chrooted
@@ -23,22 +23,22 @@ fi
 ######################################################
 timedatectl set-timezone Europe/London
 report "Set timezone" "Couldn't set timezone"
-sed -i 's/#en_GB.UTF-8/en_GB.UTF.8/' /etc/locale.gen
-sed -i 's/#el_GR.UTF-8/el_GR.UTF.8/' /etc/locale.gen
+sed -i 's/#en_GB.UTF-8/en_GB.UTF-8/' /etc/locale.gen
+sed -i 's/#el_GR.UTF-8/el_GR.UTF-8/' /etc/locale.gen
 locale-gen
 report "Generated locale" "Couldn't generate locale"
-echo LANG=en_GB.UTF-8 > /etc/locale.conf
+echo LANG=en_GB.UTF-8 >/etc/locale.conf
 export LANG=en_GB.UTF-8
 ######################################################
 # configure networking
 ######################################################
 read -p "Input a hostname: " hostname
-touch /etc/hostname && \
-    echo "$hostname" > /etc/hostname
+touch /etc/hostname &&
+    echo "$hostname" >/etc/hostname
 report "Wrote hostname $hostname to /etc/hostname" "Couldn't write hostname to /etc/hostname"
 
 touch /etc/hosts
-cat <<EOT >> /etc/hosts
+cat <<EOT >>/etc/hosts
 127.0.0.1       localhost
 192.168.1.1     router
 192.168.1.112   ace
@@ -61,7 +61,7 @@ report "Updated sudoers" "Couldn't update sudoers"
 ######################################################
 # Binds for /etc/fstab
 ######################################################
-cat <<EOT >> /etc/fstab
+cat <<EOT >>/etc/fstab
 
 # Binds for data partition
 /mnt/data/Documents	/home/simon/Documents	none	defaults,bind 0	0
@@ -76,30 +76,27 @@ report "Added binds for home directory" "Couldn't add binds for home directory"
 # Install various packages
 ######################################################
 packages="lightdm iwd dhcpcd openssh fzf ranger alsa-utils mpd mpc ncmpcpp w3m xorg xorg-xserver xorg-xsettool libx11 libxft libxrandr libxext imagemagick rtv surfraw mupdf tmux catdoc atool highlight mediainfo perl-image-exiftool odt2txt docx2txt cups sxiv mpv sxhkd python-pip ttf-ubuntu-font-family ttf-dejavu ttf-liberation ttf-fira-code nfs-utils acpi base-devel dmenu slock pass git stow rsync gtk2"
-for package in $packages
-do
+for package in $packages; do
     pacman -Ss $package
-    [ $? -eq 0 ] && pacman -S --noconfirm $package && echo "Installed package $package" >> $LOG || echo "Couldn't find package $package" >> $LOG
+    [ $? -eq 0 ] && pacman -S --noconfirm $package && echo "Installed package $package" >>$LOG || echo "Couldn't find package $package" >>$LOG
 done
 ######################################################
 # Enable packages
 ######################################################
 services="lightdm org.cups.cupsd iwd dhcpcd sshd"
-for service in $services
-do
+for service in $services; do
     systemctl enable $service
     report "Installed service $service" "Couldn't install service $service"
 done
 ######################################################
-# pip install python 
+# pip install python
 ######################################################
 pippackages="youtube-dl mps-youtube xlsx2csv"
-for pippkg in $pippackages
-do
+for pippkg in $pippackages; do
     pip install $pippkg
     report "Installed pip package $pippkg" "Couldn't install pip package $pippkg"
 done
-## lightdm should now be able to start dwm. 
+## lightdm should now be able to start dwm.
 ## If it doesn't, check .xsession-errors. Errors raised by .profile (including
 ## errors from sourced files (oops!)) can prevent launching.
 
@@ -114,7 +111,7 @@ done
 useradd -m simon
 sudo -i -u simon bash <<EOT
 mkdir .local .config .vim .vim/bundle .emacs.d .emacs.d/private
-git clone http://192.168.1.103/git/private-ace.git ~/.private
+git clone http://192.168.1.210/git/private-ace.git ~/.private
 mv ~/.ssh ~/ssh.bak
 cd ~/.private && stow *
 git clone https://github.com/jsMRSoL/dotfiles.git ~/.dotfiles
@@ -123,7 +120,7 @@ cd ~/.dotfiles && stow *
 # vundle!
 git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
 EOT
-exit
+# exit
 # permissions on .ssh/{keys} must be 600
 # permissions on .gnupg must be 700
 # permissions on .gnupg must be 600
@@ -154,29 +151,28 @@ cd $DOTFILES/suckless/.config/suckless/dwm
 make clean install
 cd $DOTFILES/suckless/.config/suckless/st
 make clean install
-<<<<<<< HEAD
 ######################################################
 # Install yay
 ######################################################
 su simon
 mkdir ~/tmp
-git clone https://aur.archlinux.org/yay.git ~/tmp/yay
-report "Downloaded yay from aur" "Couldn't download yay from aur"
-cd ~/tmp/yay
+git clone https://aur.archlinux.org/paru-bin.git ~/tmp/paru-bin
+report "Downloaded paru-bin from aur" "Couldn't download paru-bin from aur"
+cd ~/tmp/paru-bin
 makepkg -si
 ######################################################
 # Install yay packages
 ######################################################
-yay-packages="lightdm-slick-greeter urlview task-spooler python-xlsx2csv ttf-ms-fonts ttf-vista-fonts"
-for yay-package in $yay-packages
-do
-    yay -S --answerclean=None --answerdiff=None --answeredit=None --answerupgrade=None $yay-package
+paru_packages="lightdm-slick-greeter urlview task-spooler python-xlsx2csv ttf-ms-fonts ttf-vista-fonts"
+for paru_package in $paru_packages; do
+    paru -S --answerclean=None --answerdiff=None --answeredit=None
+    --answerupgrade=None $paru_package
 done
 
 ######################################################
 # Further notes
 ######################################################
-# 
+#
 # ssh keyless login
 # generate keys (accept all defaults)
 # ssh-keygen -t rsa
